# Generated by Django 5.0.1 on 2024-07-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubCert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('post_office', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
