# Generated by Django 5.0.1 on 2024-07-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubCert', '0002_companyrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
