# Generated by Django 5.0.1 on 2024-07-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubCert', '0004_automaticlogin_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automaticlogin',
            name='request',
        ),
    ]
