# Generated by Django 5.0.1 on 2024-08-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubCert', '0006_myverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
